Repository vvo/selenium-standalone, pull requests merged in 2018-06, with the labels that each got.

#364 recognise MicrosoftWebDriver 17134
  lib/microsoft-edge-releases.js
Labels: area: driver incompatibility

#366 Update default chromedriver to 2.39
  README.md
  lib/default-config.js
Labels: area: driver upgrade

#370 Docker support
  .dockerignore
  Dockerfile
  README.md
Labels: area: docker
